"""Public Hikvision adapter API."""

from .adapter import HikvisionAdapter, playback_locator_for_device_time
from .discovery import discover_devices, parse_discovery_response
from .errors import (
    AuthenticationError,
    HikvisionError,
    PaginationError,
    ResponseLimitError,
    UnsafePayloadError,
    UpstreamError,
)
from .models import (
    CapabilityEvidence,
    CapabilityReport,
    ClockObservation,
    ConnectionConfig,
    DeviceIdentity,
    DiscoveredDevice,
    EventAuditReport,
    EventRuleStatus,
    HistoricalEvent,
    HistoricalEventQuery,
    HistoricalEventResult,
    MediaChannel,
    MediaResolution,
    Page,
    RecordingQuery,
    RecordingSpan,
    RuleOverlay,
)
from .transport import DigestTransport, HttpResponse, Transport

__all__ = [
    "AuthenticationError",
    "CapabilityEvidence",
    "CapabilityReport",
    "ClockObservation",
    "ConnectionConfig",
    "DeviceIdentity",
    "DiscoveredDevice",
    "EventAuditReport",
    "EventRuleStatus",
    "HistoricalEvent",
    "HistoricalEventQuery",
    "HistoricalEventResult",
    "DigestTransport",
    "HikvisionAdapter",
    "discover_devices",
    "parse_discovery_response",
    "HikvisionError",
    "HttpResponse",
    "MediaChannel",
    "MediaResolution",
    "Page",
    "PaginationError",
    "RecordingQuery",
    "RecordingSpan",
    "RuleOverlay",
    "playback_locator_for_device_time",
    "ResponseLimitError",
    "Transport",
    "UnsafePayloadError",
    "UpstreamError",
]
