import { type FormEvent, useEffect, useState } from "react";
import type { NoticeSetter } from "../App";
import { ApiError, api, patch, post } from "../api";
import { CameraSnapshot } from "../CameraSnapshot";
import { useLoad } from "../hooks";
import { eventCategory, eventPresentation, nvrProbePayload, type NvrConnectionForm } from "../lib";
import type { Channel, DiscoveredDevice, EventAudit, EventRule, Nvr } from "../types";
import { Badge, Button, Header, Problem, Spinner, card, field } from "../ui";

const emptyForm: NvrConnectionForm = { name: "", host: "", username: "", password: "", http_port: 80, use_https: false, verify_tls: true };

export function DevicesPage({ setNotice }: { setNotice: NoticeSetter }) {
  const nvrs = useLoad(() => api<Nvr[]>("/nvrs"));
  const [discovered, setDiscovered] = useState<DiscoveredDevice[]>([]);
  const [discovering, setDiscovering] = useState(false);
  const [form, setForm] = useState<NvrConnectionForm>(emptyForm);
  const [probe, setProbe] = useState<Record<string, unknown> | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<ApiError | null>(null);
  const [channels, setChannels] = useState<Record<string, Channel[]>>({});
  const [audits, setAudits] = useState<Record<string, EventAudit>>({});
  const [auditBusy, setAuditBusy] = useState<string | null>(null);

  useEffect(() => { void discover(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => {
    for (const nvr of nvrs.data ?? []) {
      api<Channel[]>(`/nvrs/${nvr.id}/channels`).then((items) => setChannels((current) => ({ ...current, [nvr.id]: items }))).catch(() => undefined);
      api<EventAudit>(`/nvrs/${nvr.id}/event-audit`).then((audit) => setAudits((current) => ({ ...current, [nvr.id]: audit }))).catch(() => undefined);
    }
  }, [nvrs.data]);

  async function discover() { setDiscovering(true); setError(null); try { setDiscovered(await post<DiscoveredDevice[]>("/nvrs/discover", { timeout_seconds: 5 })); } catch (caught) { setError(caught as ApiError); } finally { setDiscovering(false); } }
  function choose(device: DiscoveredDevice) { setForm({ ...emptyForm, name: device.model || device.name.replace(/^ISAPI candidate /, "NVR "), host: device.host, http_port: device.http_port, use_https: device.use_https, verify_tls: device.use_https }); setProbe(null); document.getElementById("device-credentials")?.scrollIntoView({ behavior: "smooth" }); }
  async function readOnlyProbe() { setBusy(true); setError(null); try { setProbe(await post("/nvrs/probe", nvrProbePayload(form))); setNotice({ tone: "success", text: "只读检测通过，设备身份和时钟已确认。" }); } catch (caught) { setError(caught as ApiError); } finally { setBusy(false); } }
  async function add(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await post("/nvrs", form); setForm(emptyForm); setProbe(null); await nvrs.refresh(); await discover(); setNotice({ tone: "success", text: "NVR 已添加，凭据已写入 Windows 安全存储。" }); } catch (caught) { setError(caught as ApiError); } finally { setBusy(false); } }
  async function sync(nvr: Nvr) { try { const items = await post<Channel[]>(`/nvrs/${nvr.id}/sync-channels`); setChannels((current) => ({ ...current, [nvr.id]: items })); setNotice({ tone: "success", text: `已同步 ${items.length} 个摄像机通道。` }); } catch (caught) { setError(caught as ApiError); } }
  async function audit(nvr: Nvr) { setAuditBusy(nvr.id); try { const report = await post<EventAudit>(`/nvrs/${nvr.id}/event-audit`); setAudits((current) => ({ ...current, [nvr.id]: report })); setNotice({ tone: "success", text: "只读事件配置扫描完成，已读取设备返回的规则区域。" }); } catch (caught) { setError(caught as ApiError); } finally { setAuditBusy(null); } }
  async function auditAll() { const configured = nvrs.data ?? []; if (!configured.length) return; setAuditBusy("all"); setError(null); try { const next = { ...audits }; for (const nvr of configured) next[nvr.id] = await post<EventAudit>(`/nvrs/${nvr.id}/event-audit`); setAudits(next); setNotice({ tone: "success", text: `已完成 ${configured.length} 台 NVR 的只读事件配置扫描。` }); } catch (caught) { setError(caught as ApiError); } finally { setAuditBusy(null); } }
  async function rename(channel: Channel) { const alias = window.prompt("摄像机名称/业务区域", channel.alias || ""); if (alias === null) return; try { const updated = await patch<Channel>(`/channels/${channel.id}`, { alias: alias.trim() || null }); setChannels((current) => ({ ...current, [channel.nvr_id]: (current[channel.nvr_id] ?? []).map((item) => item.id === channel.id ? updated : item) })); } catch (caught) { setError(caught as ApiError); } }
  async function remove(nvr: Nvr) { if (!window.confirm(`删除“${nvr.name}”？关联搜索记录与本地派生片段也会删除，NVR 原始录像不受影响。`)) return; try { await api(`/nvrs/${nvr.id}`, { method: "DELETE" }); await nvrs.refresh(); await discover(); setNotice({ tone: "success", text: "设备及本地关联数据已删除，NVR 原始录像未改动。" }); } catch (caught) { setError(caught as ApiError); } }

  return <>
    <Header eyebrow="DEVICE CENTER" title="设备中心" description="自动搜索局域网设备；摄像机优先显示低码率画面，权限不足时使用最近录像识别图，并合并事件规则与通知状态。" action={<div className="flex flex-wrap gap-2"><Button onClick={auditAll} disabled={auditBusy !== null || !nvrs.data?.length}>{auditBusy === "all" ? "扫描事件配置中…" : "扫描所有事件配置"}</Button><Button onClick={discover} disabled={discovering}>{discovering ? "扫描设备中…" : "重新扫描局域网"}</Button></div>} />
    <Problem error={error ?? nvrs.error} />
    <section className={`${card} p-5 sm:p-7`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">局域网设备</h2><p className="mt-1 text-sm text-slate-600">ONVIF WS-Discovery 优先；未发现时仍可手动填写地址。</p></div>{discovering && <Spinner label="正在发现设备（最多 5 秒）" />}</div>{!discovering && discovered.length === 0 ? <div className="mt-5 rounded-xl border border-dashed border-slate-300 p-6 text-sm text-slate-600">没有自动发现设备。可能位于不同 VLAN、关闭了 ONVIF 或使用非 80 端口。</div> : <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{discovered.map((device) => <button type="button" key={`${device.host}:${device.http_port}:${device.use_https}`} onClick={() => choose(device)} disabled={device.already_added} className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-left transition hover:border-emerald-500 hover:bg-emerald-50 disabled:cursor-default disabled:opacity-60"><div className="flex items-start justify-between gap-2"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#173b34] text-white">▣</span><Badge tone={device.already_added ? "positive" : device.discovery_protocol === "onvif_ws_discovery" ? "positive" : "warning"}>{device.already_added ? "已添加" : device.discovery_protocol === "onvif_ws_discovery" ? "ONVIF" : "待验证 ISAPI"}</Badge></div><strong className="mt-3 block truncate">{device.model || device.name}</strong><span className="mt-1 block font-mono text-xs text-slate-500">{device.use_https ? "https" : "http"}://{device.host}:{device.http_port}</span></button>)}</div>}</section>
    <form id="device-credentials" onSubmit={add} className={`${card} mt-5 p-5 sm:p-7`}><div className="mb-5"><h2 className="text-xl font-bold">验证并添加</h2><p className="mt-1 text-sm text-slate-600">只读检测不会保存凭据；确认后密码只进入 Windows DPAPI 安全存储。</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="显示名称" value={form.name} onChange={(name) => setForm({ ...form, name })} placeholder="例如：一号楼 NVR" /><Field label="NVR 地址" value={form.host} onChange={(host) => setForm({ ...form, host })} placeholder="192.168.1.64" /><label className="text-sm font-semibold text-slate-700">HTTP(S) 端口<input required type="number" min="1" max="65535" className={`${field} mt-2`} value={form.http_port} onChange={(event) => setForm({ ...form, http_port: Number(event.target.value) })} /></label><Field label="用户名" value={form.username} onChange={(username) => setForm({ ...form, username })} autoComplete="username" /><Field label="密码" value={form.password} onChange={(password) => setForm({ ...form, password })} type="password" autoComplete="current-password" /></div><div className="mt-5 flex flex-wrap gap-5"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.use_https} onChange={(event) => setForm({ ...form, use_https: event.target.checked })} />使用 HTTPS</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.verify_tls} disabled={!form.use_https} onChange={(event) => setForm({ ...form, verify_tls: event.target.checked })} />验证 TLS 证书</label></div>{probe && <div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><strong>只读检测已通过</strong><p className="mt-1">可以确认添加。</p></div>}<div className="mt-5 flex gap-3"><Button type="button" onClick={readOnlyProbe} disabled={busy || !form.host || !form.username || !form.password}>只读检测</Button><Button variant="primary" type="submit" disabled={busy || !form.host || !form.username || !form.password}>{busy ? "处理中…" : "确认添加"}</Button></div></form>
    <section className="mt-8"><h2 className="mb-4 text-2xl font-bold">已配置设备 <span className="text-base font-normal text-slate-500">{nvrs.data?.length ?? 0}</span></h2><div className="space-y-5">{nvrs.data?.map((nvr) => <ConfiguredDevice key={nvr.id} nvr={nvr} channels={channels[nvr.id] ?? []} audit={audits[nvr.id]} auditBusy={auditBusy === nvr.id || auditBusy === "all"} onSync={() => sync(nvr)} onAudit={() => audit(nvr)} onRename={rename} onRemove={() => remove(nvr)} />)}</div></section>
  </>;
}

function Field({ label, onChange, ...props }: { label: string; onChange: (value: string) => void } & Omit<React.InputHTMLAttributes<HTMLInputElement>, "onChange">) { return <label className="text-sm font-semibold text-slate-700">{label}<input required className={`${field} mt-2`} onChange={(event) => onChange(event.target.value)} {...props} /></label>; }

function ConfiguredDevice({ nvr, channels, audit, auditBusy, onSync, onAudit, onRename, onRemove }: { nvr: Nvr; channels: Channel[]; audit?: EventAudit; auditBusy: boolean; onSync: () => void; onAudit: () => void; onRename: (channel: Channel) => void; onRemove: () => void }) {
  return <article className={`${card} p-5 sm:p-7`}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-bold">{nvr.name}</h3><Badge tone="positive">已连接</Badge></div><p className="mt-1 text-xs text-slate-500">{nvr.model || "型号未知"} · {nvr.firmware || "固件未知"} · {channels.length} 个摄像机</p></div><div className="flex flex-wrap gap-2"><Button onClick={onSync}>同步通道</Button><Button onClick={onAudit} disabled={auditBusy}>{auditBusy ? "扫描配置中…" : "扫描事件配置"}</Button><Button variant="danger" onClick={onRemove}>删除设备</Button></div></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{channels.map((channel) => <ChannelRuleCard key={channel.id} channel={channel} rules={audit?.rules.filter((rule) => rule.channel_external_id === channel.external_channel_id) ?? []} onRename={() => onRename(channel)} />)}{channels.length === 0 && <p className="rounded-xl border border-dashed p-5 text-sm text-slate-500">尚未同步到通道。</p>}</div></article>;
}

function ChannelRuleCard({ channel, rules, onRename }: { channel: Channel; rules: EventRule[]; onRename: () => void }) {
  const [selected, setSelected] = useState(rules[0]?.event_type || "");
  useEffect(() => { if (!rules.some((rule) => rule.event_type === selected)) setSelected(rules[0]?.event_type || ""); }, [rules, selected]);
  const active = rules.find((rule) => rule.event_type === selected);
  const ordinary = rules.filter((rule) => eventCategory(rule.event_type) === "ordinary");
  const smart = rules.filter((rule) => eventCategory(rule.event_type) === "smart");
  const capabilitySummary = (items: EventRule[]) => items.map((rule) => <span key={rule.event_type} className="flex items-center justify-between gap-2 text-xs"><span>{eventPresentation(rule.event_type)}</span><Badge tone={rule.state === "supported" ? rule.enabled ? "positive" : "neutral" : "warning"}>{rule.state === "supported" ? rule.enabled ? "已启用" : "支持·未启用" : "不支持/未知"}</Badge></span>);
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-slate-50"><CameraSnapshot channel={channel} overlays={active?.overlays ?? []} /><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h4 className="font-bold">{channel.alias || "未命名摄像机"}</h4><p className="mt-1 text-xs text-slate-500">{channel.online ? "在线" : "状态未知/离线"} · 设备通道 {channel.external_channel_id}</p></div><Button variant="ghost" onClick={onRename}>重命名</Button></div>{rules.length ? <div className="mt-4"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-3"><strong className="mb-2 block text-xs">普通事件</strong><div className="space-y-2">{capabilitySummary(ordinary)}</div></div><div className="rounded-xl border border-amber-200 bg-amber-50/60 p-3"><strong className="mb-2 block text-xs">Smart 事件</strong><div className="space-y-2">{capabilitySummary(smart)}</div></div></div><label className="mt-4 block text-xs font-semibold text-slate-600">在画面查看规则边界<select className={`${field} mt-1`} value={selected} onChange={(event) => setSelected(event.target.value)}><optgroup label="普通事件">{ordinary.map((rule) => <option key={rule.event_type} value={rule.event_type}>{eventPresentation(rule.event_type)}</option>)}</optgroup><optgroup label="Smart 事件">{smart.map((rule) => <option key={rule.event_type} value={rule.event_type}>{eventPresentation(rule.event_type)}</option>)}</optgroup></select></label>{active && <div className="mt-3 flex flex-wrap gap-2"><Badge tone={eventCategory(active.event_type) === "smart" ? "warning" : "neutral"}>{eventCategory(active.event_type) === "smart" ? "Smart 事件" : "普通事件"}</Badge><Badge tone={active.enabled ? "positive" : active.enabled === false ? "neutral" : "warning"}>{active.enabled ? "已启用" : active.enabled === false ? "未启用" : "状态未知"}</Badge><Badge tone={active.notification_configured ? "positive" : "warning"}>{active.notification_configured ? "通知已联动" : active.notification_configured === false ? "通知未配置" : "通知未知"}</Badge><Badge>{active.overlays.length ? `${active.overlays.length} 组画面区域` : "设备未返回画面边界"}</Badge></div>}</div> : <p className="mt-4 rounded-xl border border-dashed border-slate-300 p-3 text-xs leading-5 text-slate-600">点击设备上的“扫描事件配置”，即可读取普通事件、Smart 事件、通知联动和规则区域。</p>}</div></section>;
}
